Keyboard control feature
ItJustWorksTM/EiffelVis pull request #117
Opened 2022-11-01 20:40 UTC by ktpa

2022-11-02 11:58 UTC, RuthgerD requested changes
Would be nice if the transition was animated but thats a thing for later.

2022-11-02 11:58 UTC, RuthgerD commented on frontend/src/components/G6Graph.svelte
> +    // This is a hack to get the graph to render properly
would prefer this to be a separate PR

2022-11-02 11:58 UTC, RuthgerD commented on frontend/src/components/G6Graph.svelte
> +            if (e.key === "ArrowRight") {
Hate to be like this but I hate if chains with repeated calls more :)
```typescript
let weight = (k1, k2) => e.key == k1 ? -1 : e.key == k2 ? 1 : 0
graph.translate(
    weight("ArrowRight", "ArrowLeft") * graph_translation,
    weight("ArrowDown", "ArrowUp") * graph_translation
)
```

2022-11-02 13:31 UTC, ktpa commented
> Would be nice if the transition was animated but thats a thing for later.

Resolved with animation_cfg.

2022-11-02 18:47 UTC, RuthgerD reviewed
Alright I tried it out locally and realized a problem with this approach, with these events you cant actually ever have 2 keys pressed at the same time; they will be separate events, causing jitter.

Its basically always locked into one dimension.
Do you think it is feasible to fix that?

2022-11-02 20:54 UTC, ktpa commented
> Alright I tried it out locally and realized a problem with this approach, with these events you cant actually ever have 2 keys pressed at the same time; they will be separate events, causing jitter.
> 
> Its basically always locked into one dimension. Do you think it is feasible to fix that?

It may be feasible but as of now, the basic functionality is there and ItJustWorks. Multiple keydowns require some more tinkering and to configure the animation beyond the scope of the framework as it currently is. I've removed the animation due to the aforementioned stuttering issue.

2022-11-03 06:19 UTC, RuthgerD approved these changes
Thanks!

2022-11-03 06:21 UTC, merged